In [1]:
# importing libraries
import pandas as pd             # data science essentials
import matplotlib.pyplot as plt # essential graphical output
import seaborn as sns           # enhanced graphical output
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

# setting pandas print options
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)


# specifying file name

file = './Flora Data Set.csv'


# reading the file into Python

flora = pd.read_csv(file)


# outputting the first ten rows of the dataset

flora.head(n=150)

     customer_id type_of_client     education         marital_status    Revenue type_of_sale    occupation_type        Country   employment_type
0              0            NaN           NaN                    NaN  890784.20           No                NaN            NaN               NaN
1         183582            NaN       HS-grad     Married-civ-spouse     959.12           No  Machine-op-inspct  United-States           Private
2        1765943            NaN       HS-grad     Married-civ-spouse      56.30           No       Adm-clerical  United-States       Federal-gov
3        3173172       Personal       Masters          Never-married       6.55           No    Exec-managerial  United-States           Private
4        9046402            NaN     Bachelors     Married-civ-spouse     147.09           No     Prof-specialty  United-States           Private
5       10304995            NaN       HS-grad     Married-civ-spouse     119.32           No    Exec-managerial  United-States           Private
6       10327107            NaN  Some-college               Divorced    1283.48           No     Prof-specialty  United-States           Private
7       10976223            NaN   Prof-school          Never-married     534.08           No    Exec-managerial           Cuba           Private
8       12065807     Wholesaler       HS-grad     Married-civ-spouse    2094.61           No   Transport-moving  United-States       Federal-gov
9       13433438            NaN       HS-grad                Widowed      98.65           No              Sales  United-States           Private
10      14694739     Wholesaler   Prof-school     Married-civ-spouse     480.30           No     Prof-specialty  United-States           Private
11      14720096            NaN       HS-grad          Never-married     171.55           No  Handlers-cleaners  United-States         Local-gov
12      16841603            NaN          12th  Married-spouse-absent     112.93           No      Other-service  United-States           Private
13      19115873            NaN       HS-grad               Divorced      80.19           No       Craft-repair  United-States           Private
14      19703136     Wholesaler  Some-college     Married-civ-spouse    2433.26           No      Other-service  United-States           Private
15      22466613     Wholesaler     Bachelors     Married-civ-spouse    3238.20           No       Tech-support  United-States           Private
16      23919928            NaN     Bachelors     Married-civ-spouse    1146.98           No     Prof-specialty  United-States         State-gov
17      24717403            NaN       HS-grad          Never-married   10102.32           No      Other-service  United-States           Private
18      24933036            NaN       HS-grad     Married-civ-spouse     316.34           No  Machine-op-inspct  United-States           Private
19      25679765            NaN  Some-college     Married-civ-spouse     417.37           No  Machine-op-inspct  United-States           Private
20      25944813            NaN    Assoc-acdm          Never-married     313.77           No  Machine-op-inspct  United-States           Private
21      26294059            NaN  Some-college          Never-married     164.05           No     Prof-specialty  United-States           Private
22      26944650            NaN           9th          Never-married     267.52           No       Craft-repair  United-States      Self-emp-inc
23      28946227            NaN       HS-grad          Never-married      -3.50       return  Handlers-cleaners  United-States           Private
24      30061301            NaN       HS-grad          Never-married     145.25           No  Machine-op-inspct  United-States           Private
25      30720771            NaN     Bachelors     Married-civ-spouse    1920.00           No              Sales  United-States           Private
26      30809284            NaN  Some-college     Married-civ-spouse   13326.58           No    Protective-serv  United-States           Private
27      31201847            NaN       Masters          Never-married    -794.38       return     Prof-specialty  United-States         Local-gov
28      32160300            NaN       HS-grad               Divorced     118.75           No     Prof-specialty  United-States           Private
29      32689318     Wholesaler       HS-grad     Married-civ-spouse     461.06           No       Adm-clerical  United-States           Private
30      34901908            NaN  Some-college          Never-married     640.01           No      Other-service  United-States           Private
31      35505250            NaN    Assoc-acdm     Married-civ-spouse     461.92           No       Craft-repair  United-States           Private
32      36656745            NaN       HS-grad               Divorced     224.30           No       Craft-repair    Puerto-Rico         Local-gov
33      36839113            NaN     Bachelors          Never-married     311.00           No    Exec-managerial  United-States           Private
34      37341880            NaN       HS-grad     Married-civ-spouse     168.48           No   Transport-moving  United-States           Private
35      37526661            NaN       HS-grad          Never-married    1009.38           No              Sales  United-States           Private
36      39687977       Personal  Some-college              Separated     271.00           No  Machine-op-inspct  United-States           Private
37      39881891            NaN     Bachelors     Married-civ-spouse     104.78           No       Adm-clerical  United-States           Private
38      41003820            NaN       HS-grad     Married-civ-spouse     112.75           No    Exec-managerial  United-States      Self-emp-inc
39      44286567            NaN       HS-grad     Married-civ-spouse       4.98           No       Craft-repair  United-States           Private
40      45516215            NaN     Bachelors               Divorced     818.44           No     Prof-specialty  United-States  Self-emp-not-inc
41      47350117     Wholesaler       7th-8th          Never-married     144.00           No  Machine-op-inspct  United-States           Private
42      48463343            NaN       Masters     Married-civ-spouse     850.67           No    Exec-managerial         France           Private
43      48841585            NaN       HS-grad     Married-civ-spouse    1005.94           No   Transport-moving  United-States           Private
44      50064665            NaN     Bachelors          Never-married      35.35           No       Adm-clerical  United-States           Private
45      51016322            NaN  Some-college          Never-married      43.99           No       Adm-clerical  United-States           Private
46      51123675            NaN     Assoc-voc     Married-civ-spouse    2020.05           No  Machine-op-inspct  United-States           Private
47      52139683            NaN       7th-8th     Married-civ-spouse     173.40           No       Craft-repair  United-States  Self-emp-not-inc
48      52684376       Personal     Bachelors          Never-married    1382.15           No    Exec-managerial  United-States           Private
49      53802868            NaN       HS-grad     Married-civ-spouse     853.11           No  Handlers-cleaners  United-States       Federal-gov
50      55507251            NaN       HS-grad     Married-civ-spouse    1373.98           No       Adm-clerical  United-States       Federal-gov
51      56208308            NaN     Bachelors          Never-married    1098.42           No     Prof-specialty  United-States           Private
52      58370272            NaN       HS-grad     Married-civ-spouse    2008.42           No   Transport-moving  United-States           Private
53      60622829            NaN     Bachelors     Married-civ-spouse     201.52           No    Exec-managerial  United-States           Private
54      61041417     Wholesaler       HS-grad     Married-civ-spouse     853.58           No              Sales  United-States           Private
55      62232944            NaN  Some-college     Married-civ-spouse     102.08           No      Other-service  United-States           Private
56      62759226            NaN     Bachelors     Married-civ-spouse     130.12           No     Prof-specialty  United-States           Private
57      63570727            NaN       HS-grad     Married-civ-spouse     877.03           No     Prof-specialty  United-States           Private
58      64086279       Personal     Bachelors     Married-civ-spouse      64.25           No    Exec-managerial  United-States      Self-emp-inc
59      64139651     Wholesaler       HS-grad          Never-married     128.07           No       Adm-clerical  United-States           Private
60      66869911            NaN       HS-grad          Never-married      28.15           No  Handlers-cleaners  United-States           Private
61      68247391            NaN  Some-college          Never-married     299.65           No       Tech-support  United-States           Private
62      69160909     Wholesaler  Some-college     Married-civ-spouse    1165.67           No       Craft-repair  United-States  Self-emp-not-inc
63      69751722     Wholesaler           9th     Married-civ-spouse     543.74           No       Craft-repair  United-States           Private
64      70533479            NaN       1st-4th          Never-married     167.99           No      Other-service    El-Salvador           Private
65      71675812     Wholesaler           9th     Married-civ-spouse      62.43           No              Sales  United-States           Private
66      75196663     Wholesaler       HS-grad     Married-civ-spouse    1045.79           No      Other-service  United-States           Private
67      76092493            NaN       HS-grad               Divorced    3770.12           No              Sales  United-States  Self-emp-not-inc
68      76530997            NaN  Some-college               Divorced    5772.15           No       Adm-clerical  United-States           Private
69      77306032            NaN          10th               Divorced    3160.76           No      Other-service  United-States           Private
70      78007635            NaN       HS-grad     Married-civ-spouse     731.43           No    Protective-serv  United-States         State-gov
71      78143806     Wholesaler       HS-grad     Married-civ-spouse    2741.36           No              Sales  United-States           Private
72      82038650     Wholesaler          11th              Separated   -1804.01       return      Other-service  United-States           Private
73      85644792            NaN  Some-college          Never-married      78.44           No    Exec-managerial  United-States           Private
74      85750314            NaN     Bachelors     Married-civ-spouse    1165.69           No    Exec-managerial  United-States           Private
75      87003906            NaN          12th     Married-civ-spouse    1745.34           No    Exec-managerial  United-States      Self-emp-inc
76      87083658     Wholesaler          11th     Married-civ-spouse    2193.95           No              Sales  United-States           Private
77      87513323            NaN     Bachelors     Married-civ-spouse     434.05           No    Exec-managerial  United-States           Private
78      87709995     Wholesaler       5th-6th     Married-civ-spouse     900.81           No   Transport-moving  United-States           Private
79      88840570            NaN  Some-college          Never-married     181.84           No              Sales  United-States           Private
80      89027990            NaN  Some-college          Never-married    4930.70           No      Other-service  United-States           Private
81      89913658            NaN       HS-grad     Married-civ-spouse       4.55           No       Craft-repair  United-States           Private
82      91426599            NaN       HS-grad     Married-civ-spouse     237.81           No       Craft-repair  United-States  Self-emp-not-inc
83      92379060            NaN       HS-grad     Married-civ-spouse      70.95           No       Craft-repair  United-States           Private
84      95995307       Personal       HS-grad          Never-married     132.26           No  Handlers-cleaners  United-States           Private
85      99816138            NaN          11th          Never-married      10.95           No              Sales  United-States           Private
86     101011975     Wholesaler  Some-college          Never-married     732.01           No    Priv-house-serv  United-States           Private
87     101173052            NaN       Masters     Married-civ-spouse     -10.17       return     Prof-specialty  United-States           Private
88     101253082            NaN       Masters     Married-civ-spouse      25.11           No       Tech-support  United-States           Private
89     101850978            NaN       HS-grad          Never-married    -248.45       return  Machine-op-inspct  United-States           Private
90     103150611            NaN       Masters     Married-civ-spouse     335.10           No     Prof-specialty  United-States         Local-gov
91     104255154            NaN     Bachelors          Never-married     151.42           No     Prof-specialty  United-States           Private
92     107460504            NaN       HS-grad     Married-civ-spouse    2507.59           No      Other-service  United-States           Private
93     107465558            NaN     Bachelors          Never-married      62.10           No     Prof-specialty        England           Private
94     107588210     Wholesaler  Some-college          Never-married    1805.35           No       Adm-clerical  United-States         State-gov
95     107672766            NaN       7th-8th                Widowed     822.60           No      Other-service  United-States           Private
96     110708885            NaN       7th-8th                Widowed    1201.20           No    Farming-fishing  United-States  Self-emp-not-inc
97     111100258            NaN     Bachelors     Married-civ-spouse     190.55           No    Exec-managerial  United-States  Self-emp-not-inc
98     111459471            NaN       Masters     Married-civ-spouse     241.85           No    Exec-managerial  United-States           Private
99     112015804            NaN    Assoc-acdm          Never-married    -300.22       return              Sales  United-States           Private
100    112104608     Wholesaler     Bachelors               Divorced     709.24           No    Protective-serv        Germany         Local-gov
101    114311630     Wholesaler       HS-grad          Never-married     424.26           No      Other-service  United-States           Private
102    115587408     Wholesaler     Assoc-voc     Married-civ-spouse     693.09           No       Craft-repair  United-States           Private
103    117931518     Wholesaler     Bachelors  Married-spouse-absent     170.83           No       Craft-repair        Ireland           Private
104    120112900     Wholesaler       Masters          Never-married    7917.70           No    Exec-managerial  United-States           Private
105    121118239     Wholesaler       HS-grad     Married-civ-spouse    1592.97           No    Farming-fishing  United-States  Self-emp-not-inc
106    121304859            NaN       HS-grad     Married-civ-spouse     133.45           No       Craft-repair  United-States           Private
107    123319488            NaN     Bachelors               Divorced      40.50           No     Prof-specialty  United-States           Private
108    124090807     Wholesaler     Bachelors     Married-civ-spouse     336.85           No     Prof-specialty  United-States           Private
109    124624567     Wholesaler          11th     Married-civ-spouse    2460.32           No       Craft-repair         Mexico           Private
110    125536607            NaN  Some-college     Married-civ-spouse     387.60           No  Handlers-cleaners  United-States       Federal-gov
111    125646095            NaN  Some-college          Never-married      98.62           No              Sales  United-States           Private
112    126598255            NaN  Some-college     Married-civ-spouse     632.45           No       Craft-repair  United-States           Private
113    126615131            NaN     Bachelors          Never-married    6090.71           No       Craft-repair  United-States  Self-emp-not-inc
114    126931851            NaN       HS-grad     Married-civ-spouse    2353.81           No              Sales  United-States           Private
115    129252282            NaN       HS-grad               Divorced      52.80           No       Adm-clerical  United-States           Private
116    129692940            NaN  Some-college     Married-civ-spouse     188.80           No       Tech-support  United-States       Federal-gov
117    132589373     Wholesaler       HS-grad               Divorced     215.82           No      Other-service          Haiti           Private
118    133112774            NaN       HS-grad     Married-civ-spouse      73.50           No       Adm-clerical  United-States       Federal-gov
119    134031909            NaN       HS-grad     Married-civ-spouse     333.92           No       Craft-repair  United-States           Private
120    135265219            NaN     Bachelors     Married-civ-spouse    1336.07           No       Tech-support  United-States           Private
121    135396224            NaN     Bachelors               Divorced     387.71           No              Sales  United-States      Self-emp-inc
122    135811562       Personal       HS-grad     Married-civ-spouse     408.92           No      Other-service  United-States           Private
123    136659062            NaN  Some-college               Divorced     739.29           No    Protective-serv  United-States      Self-emp-inc
124    137702884            NaN       HS-grad               Divorced     179.73           No   Transport-moving  United-States         Local-gov
125    137797781            NaN       HS-grad               Divorced    1086.44           No  Handlers-cleaners  United-States           Private
126    138320676            NaN       HS-grad     Married-civ-spouse     329.87           No    Protective-serv  United-States           Private
127    139062032            NaN       HS-grad          Never-married    -102.00       return    Exec-managerial  United-States           Private
128    141887042     Wholesaler  Some-college     Married-civ-spouse     468.30           No              Sales  United-States      Self-emp-inc
129    142951373            NaN  Some-college          Never-married     324.78           No   Transport-moving  United-States           Private
130    143666855            NaN       HS-grad          Never-married      39.45           No      Other-service  United-States           Private
131    144057740     Wholesaler     Bachelors          Never-married     135.71           No      Other-service  United-States           Private
132    144068819            NaN  Some-college     Married-civ-spouse     123.40           No       Craft-repair  United-States           Private
133    145430129            NaN       HS-grad     Married-civ-spouse     272.61           No    Farming-fishing  United-States           Private
134    145564184     Wholesaler       HS-grad          Never-married    1340.23           No              Sales  United-States           Private
135    146059719            NaN       HS-grad     Married-civ-spouse     262.51           No   Transport-moving  United-States           Private

In [4]:
#creating binaries variables for each cathegorical field
#saving the new data frame into flora1
flora1=pd.DataFrame()
flora1['b_US'] = np.where(flora['Country']=='United-States', 1, 0)
flora1['b_not_US'] = np.where(flora['Country']!='United-States', 1, 0)
flora1['b_Self_emp_not_inc'] = np.where(flora['employment_type']=='Self-emp-not-inc', 1, 0)
flora1['b_Self_emp_inc'] = np.where(flora['employment_type']=='Self-emp-inc', 1, 0)
flora1['b_Without_pay'] = np.where(flora['employment_type']=='Without-pay', 1, 0)
flora1['b_Local_gov'] = np.where(flora['employment_type']=='Local-gov', 1, 0)
flora1['b_State_gov'] = np.where(flora['employment_type']=='State-gov', 1, 0) 
flora1['b_Federal_gov'] = np.where(flora['employment_type']=='Federal-gov', 1, 0) 
flora1['b_Private'] = np.where(flora['employment_type']=='Private', 1, 0)
flora1['b_Machine_op_inspct'] = np.where(flora['occupation_type']=='Machine-op-inspct', 1, 0)
flora1['b_Adm_clerical'] = np.where(flora['occupation_type']=='Adm-clerical', 1, 0)
flora1['b_Craft_repair'] = np.where(flora['occupation_type']=='Craft-repair', 1, 0)
flora1['b_Exec_managerial'] = np.where(flora['occupation_type']=='Exec-managerial', 1, 0)
flora1['b_Farming_fishing'] = np.where(flora['occupation_type']=='Farming-fishing', 1, 0)
flora1['b_Handlers_cleaners'] = np.where(flora['occupation_type']=='Handlers-cleaners', 1, 0)
flora1['b_Other_service'] = np.where(flora['occupation_type']=='Other-service', 1, 0)
flora1['b_Prof_speciality'] = np.where(flora['occupation_type']=='Prof-speciality', 1, 0)
flora1['b_Protective_serv'] = np.where(flora['occupation_type']=='Protective-serv', 1, 0)
flora1['b_Sales'] = np.where(flora['occupation_type']=='Sales', 1, 0)
flora1['b_Tech_support'] = np.where(flora['occupation_type']=='Tech-support', 1, 0)
flora1['b_Transport_moving'] = np.where(flora['occupation_type']=='Transport-moving', 1, 0)
flora1['b_Divorced'] = np.where(flora['marital_status']=='Divorced', 1, 0)
flora1['b_Married_civ_spouse'] = np.where(flora['marital_status']=='Married-civ-spouse', 1, 0)
flora1['b_Never_married'] = np.where(flora['marital_status']=='Never-married', 1, 0)
flora1['b_Widowed'] = np.where(flora['marital_status']=='Widowed', 1, 0)
flora1['b_Separated'] = np.where(flora['marital_status']=='Separated', 1, 0)
flora1['b_11th'] = np.where(flora['education']=='11th', 1, 0)
flora1['b_Assoc_acdm'] = np.where(flora['education']=='Assoc-acdm', 1, 0)
flora1['b_Bachelors'] = np.where(flora['education']=='Bachelors', 1, 0)
flora1['b_HS_grad'] = np.where(flora['education']=='HS-grad', 1, 0)
flora1['b_Some_college'] = np.where(flora['education']=='Some-college', 1, 0)
flora1['b_10th'] = np.where(flora['education']=='10th', 1, 0)
flora1['b_12th'] = np.where(flora['education']=='12th', 1, 0)
flora1['b_1st_4th'] = np.where(flora['education']=='1st-4th', 1, 0)
flora1['b_5th_6th'] = np.where(flora['education']=='5th-6th', 1, 0)
flora1['b_7th_8th'] = np.where(flora['education']=='7th-8th', 1, 0)
flora1['b_9th'] = np.where(flora['education']=='9th', 1, 0)
flora1['b_Masters'] = np.where(flora['education']=='Masters', 1, 0)
flora1['b_Doctorate'] = np.where(flora['education']=='Doctorate', 1, 0)
flora1['b_Prof_school'] = np.where(flora['education']=='Prof-school', 1, 0)
flora1['b_revenue']=abs(flora['Revenue'])
flora1['b_return'] = np.where(flora['Revenue'].astype(float)<=0, 1, 0)
flora1['type_of_client'] = flora['type_of_client']

#showing the first 100 rows of the new dataframe
flora1.head(n=100)

    b_US  b_not_US  b_Self_emp_not_inc  b_Self_emp_inc  b_Without_pay  b_Local_gov  b_State_gov  b_Federal_gov  b_Private  b_Machine_op_inspct  b_Adm_clerical  b_Craft_repair  b_Exec_managerial  b_Farming_fishing  b_Handlers_cleaners  b_Other_service  b_Prof_speciality  b_Protective_serv  b_Sales  b_Tech_support  b_Transport_moving  b_Divorced  b_Married_civ_spouse  b_Never_married  b_Widowed  b_Separated  b_11th  b_Assoc_acdm  b_Bachelors  b_HS_grad  b_Some_college  b_10th  b_12th  b_1st_4th  b_5th_6th  b_7th_8th  b_9th  b_Masters  b_Doctorate  b_Prof_school  b_revenue  b_return type_of_client
0      0         1                   0               0              0            0            0              0          0                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                0          0            0       0             0            0          0               0       0       0          0          0          0      0          0            0              0  890784.20         0            NaN
1      1         0                   0               0              0            0            0              0          1                    1               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     959.12         0            NaN
2      1         0                   0               0              0            0            0              1          0                    0               1               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0      56.30         0            NaN
3      1         0                   0               0              0            0            0              0          1                    0               0               0                  1                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               0       0       0          0          0          0      0          1            0              0       6.55         0       Personal
4      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            1          0               0       0       0          0          0          0      0          0            0              0     147.09         0            NaN
5      1         0                   0               0              0            0            0              0          1                    0               0               0                  1                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     119.32         0            NaN
6      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           1                     0                0          0            0       0             0            0          0               1       0       0          0          0          0      0          0            0              0    1283.48         0            NaN
7      0         1                   0               0              0            0            0              0          1                    0               0               0                  1                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               0       0       0          0          0          0      0          0            0              1     534.08         0            NaN
8      1         0                   0               0              0            0            0              1          0                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   1           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0    2094.61         0     Wholesaler
9      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        1               0                   0           0                     0                0          1            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0      98.65         0            NaN
10     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          0               0       0       0          0          0          0      0          0            0              1     480.30         0     Wholesaler
11     1         0                   0               0              0            1            0              0          0                    0               0               0                  0                  0                    1                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     171.55         0            NaN
12     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                1                  0                  0        0               0                   0           0                     0                0          0            0       0             0            0          0               0       0       1          0          0          0      0          0            0              0     112.93         0            NaN
13     1         0                   0               0              0            0            0              0          1                    0               0               1                  0                  0                    0                0                  0                  0        0               0                   0           1                     0                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0      80.19         0            NaN
14     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                1                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          0               1       0       0          0          0          0      0          0            0              0    2433.26         0     Wholesaler
15     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               1                   0           0                     1                0          0            0       0             0            1          0               0       0       0          0          0          0      0          0            0              0    3238.20         0     Wholesaler
16     1         0                   0               0              0            0            1              0          0                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            1          0               0       0       0          0          0          0      0          0            0              0    1146.98         0            NaN
17     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                1                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0   10102.32         0            NaN
18     1         0                   0               0              0            0            0              0          1                    1               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     316.34         0            NaN
19     1         0                   0               0              0            0            0              0          1                    1               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          0               1       0       0          0          0          0      0          0            0              0     417.37         0            NaN
20     1         0                   0               0              0            0            0              0          1                    1               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             1            0          0               0       0       0          0          0          0      0          0            0              0     313.77         0            NaN
21     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               1       0       0          0          0          0      0          0            0              0     164.05         0            NaN
22     1         0                   0               1              0            0            0              0          0                    0               0               1                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               0       0       0          0          0          0      1          0            0              0     267.52         0            NaN
23     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    1                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0       3.50         1            NaN
24     1         0                   0               0              0            0            0              0          1                    1               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     145.25         0            NaN
25     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        1               0                   0           0                     1                0          0            0       0             0            1          0               0       0       0          0          0          0      0          0            0              0    1920.00         0            NaN
26     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  1        0               0                   0           0                     1                0          0            0       0             0            0          0               1       0       0          0          0          0      0          0            0              0   13326.58         0            NaN
27     1         0                   0               0              0            1            0              0          0                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               0       0       0          0          0          0      0          1            0              0     794.38         1            NaN
28     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           1                     0                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     118.75         0            NaN
29     1         0                   0               0              0            0            0              0          1                    0               1               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     461.06         0     Wholesaler
30     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                1                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               1       0       0          0          0          0      0          0            0              0     640.01         0            NaN
31     1         0                   0               0              0            0            0              0          1                    0               0               1                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             1            0          0               0       0       0          0          0          0      0          0            0              0     461.92         0            NaN

In [11]:
#inspetting the new dataframe
flora1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4099 entries, 0 to 4098
Data columns (total 41 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   b_US                  4099 non-null   int32
 1   b_not_US              4099 non-null   int32
 2   b_Self_emp_not_inc    4099 non-null   int32
 3   b_Self_emp_inc        4099 non-null   int32
 4   b_Without_pay         4099 non-null   int32
 5   b_Local_gov           4099 non-null   int32
 6   b_State_gov           4099 non-null   int32
 7   b_Federal_gov         4099 non-null   int32
 8   b_Private             4099 non-null   int32
 9   b_Machine_op_inspct   4099 non-null   int32
 10  b_Adm_clerical        4099 non-null   int32
 11  b_Craft_repair        4099 non-null   int32
 12  b_Exec_managerial     4099 non-null   int32
 13  b_Farming_fishing     4099 non-null   int32
 14  b_Handlers_cleaners   4099 non-null   int32
 15  b_Other_service       4099 non-null   int32
 16  b_Prof_speciality     4099 non-null   int32
 17  b_Protective_serv     4099 non-null   int32
 18  b_Sales               4099 non-null   int32
 19  b_Tech_support        4099 non-null   int32
 20  b_Transport_moving    4099 non-null   int32
 21  b_Divorced            4099 non-null   int32
 22  b_Married_civ_spouse  4099 non-null   int32
 23  b_Never_married       4099 non-null   int32
 24  b_Widowed             4099 non-null   int32
 25  b_Separated           4099 non-null   int32
 26  b_11th                4099 non-null   int32
 27  b_Assoc_acdm          4099 non-null   int32
 28  b_Bachelors           4099 non-null   int32
 29  b_HS_grad             4099 non-null   int32
 30  b_Some_college        4099 non-null   int32
 31  b_10th                4099 non-null   int32
 32  b_12th                4099 non-null   int32
 33  b_1st_4th             4099 non-null   int32
 34  b_5th_6th             4099 non-null   int32
 35  b_7th_8th             4099 non-null   int32
 36  b_9th                 4099 non-null   int32
 37  b_Masters             4099 non-null   int32
 38  b_Doctorate           4099 non-null   int32
 39  b_Prof_school         4099 non-null   int32
 40  type_of_client        983 non-null    object
dtypes: int32(40), object(1)
memory usage: 672.6+ KB

In [5]:
#understanding the size and features of the new dataset
print(f"""
Size of Original Dataset
------------------------
Observations: {flora1.shape[0]}
Features:     {flora1.shape[1]}
""")

Size of Original Dataset
------------------------
Observations: 4099
Features:     43

In [6]:
#dropping the NaN from the dataset, we'll work just with observations with a type_of_client already assigned
flora_as=flora1.dropna()

#turning type_of_client in binary
#this step has to be done after Nas dropping
flora_as['type_of_client'] = np.where(flora_as['type_of_client']=='Wholesaler', 1, 0)

#showing first 50 lines of flora1
flora_as.head(n=50)

<ipython-input-6-af31ec3892c8>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flora_as['type_of_client'] = np.where(flora_as['type_of_client']=='Wholesaler', 1, 0)

     b_US  b_not_US  b_Self_emp_not_inc  b_Self_emp_inc  b_Without_pay  b_Local_gov  b_State_gov  b_Federal_gov  b_Private  b_Machine_op_inspct  b_Adm_clerical  b_Craft_repair  b_Exec_managerial  b_Farming_fishing  b_Handlers_cleaners  b_Other_service  b_Prof_speciality  b_Protective_serv  b_Sales  b_Tech_support  b_Transport_moving  b_Divorced  b_Married_civ_spouse  b_Never_married  b_Widowed  b_Separated  b_11th  b_Assoc_acdm  b_Bachelors  b_HS_grad  b_Some_college  b_10th  b_12th  b_1st_4th  b_5th_6th  b_7th_8th  b_9th  b_Masters  b_Doctorate  b_Prof_school  b_revenue  b_return  type_of_client
3       1         0                   0               0              0            0            0              0          1                    0               0               0                  1                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               0       0       0          0          0          0      0          1            0              0       6.55         0               0
8       1         0                   0               0              0            0            0              1          0                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   1           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0    2094.61         0               1
10      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          0               0       0       0          0          0          0      0          0            0              1     480.30         0               1
14      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                1                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          0               1       0       0          0          0          0      0          0            0              0    2433.26         0               1
15      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               1                   0           0                     1                0          0            0       0             0            1          0               0       0       0          0          0          0      0          0            0              0    3238.20         0               1
29      1         0                   0               0              0            0            0              0          1                    0               1               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     461.06         0               1
36      1         0                   0               0              0            0            0              0          1                    1               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                0          0            1       0             0            0          0               1       0       0          0          0          0      0          0            0              0     271.00         0               0
41      1         0                   0               0              0            0            0              0          1                    1               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               0       0       0          0          0          1      0          0            0              0     144.00         0               1
48      1         0                   0               0              0            0            0              0          1                    0               0               0                  1                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            1          0               0       0       0          0          0          0      0          0            0              0    1382.15         0               0
54      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        1               0                   0           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     853.58         0               1
58      1         0                   0               1              0            0            0              0          0                    0               0               0                  1                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            1          0               0       0       0          0          0          0      0          0            0              0      64.25         0               0
59      1         0                   0               0              0            0            0              0          1                    0               1               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     128.07         0               1
62      1         0                   1               0              0            0            0              0          0                    0               0               1                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          0               1       0       0          0          0          0      0          0            0              0    1165.67         0               1
63      1         0                   0               0              0            0            0              0          1                    0               0               1                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          0               0       0       0          0          0          0      1          0            0              0     543.74         0               1
65      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        1               0                   0           0                     1                0          0            0       0             0            0          0               0       0       0          0          0          0      1          0            0              0      62.43         0               1
66      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                1                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0    1045.79         0               1
71      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        1               0                   0           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0    2741.36         0               1
72      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                1                  0                  0        0               0                   0           0                     0                0          0            1       1             0            0          0               0       0       0          0          0          0      0          0            0              0    1804.01         1               1
76      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        1               0                   0           0                     1                0          0            0       1             0            0          0               0       0       0          0          0          0      0          0            0              0    2193.95         0               1
78      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   1           0                     1                0          0            0       0             0            0          0               0       0       0          0          1          0      0          0            0              0     900.81         0               1
84      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    1                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     132.26         0               0
86      1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               1       0       0          0          0          0      0          0            0              0     732.01         0               1
94      1         0                   0               0              0            0            1              0          0                    0               1               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               1       0       0          0          0          0      0          0            0              0    1805.35         0               1
100     0         1                   0               0              0            1            0              0          0                    0               0               0                  0                  0                    0                0                  0                  1        0               0                   0           1                     0                0          0            0       0             0            1          0               0       0       0          0          0          0      0          0            0              0     709.24         0               1
101     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                1                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     424.26         0               1
102     1         0                   0               0              0            0            0              0          1                    0               0               1                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          0               0       0       0          0          0          0      0          0            0              0     693.09         0               1
103     0         1                   0               0              0            0            0              0          1                    0               0               1                  0                  0                    0                0                  0                  0        0               0                   0           0                     0                0          0            0       0             0            1          0               0       0       0          0          0          0      0          0            0              0     170.83         0               1
104     1         0                   0               0              0            0            0              0          1                    0               0               0                  1                  0                    0                0                  0                  0        0               0                   0           0                     0                1          0            0       0             0            0          0               0       0       0          0          0          0      0          1            0              0    7917.70         0               1
105     1         0                   1               0              0            0            0              0          0                    0               0               0                  0                  1                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0    1592.97         0               1
108     1         0                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       0             0            1          0               0       0       0          0          0          0      0          0            0              0     336.85         0               1
109     0         1                   0               0              0            0            0              0          1                    0               0               1                  0                  0                    0                0                  0                  0        0               0                   0           0                     1                0          0            0       1             0            0          0               0       0       0          0          0          0      0          0            0              0    2460.32         0               1
117     0         1                   0               0              0            0            0              0          1                    0               0               0                  0                  0                    0                1                  0                  0        0               0                   0           1                     0                0          0            0       0             0            0          1               0       0       0          0          0          0      0          0            0              0     215.82         0               1

In [14]:
#inspecting the new dataset
flora_as.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 983 entries, 3 to 4095
Data columns (total 41 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   b_US                  983 non-null    int32
 1   b_not_US              983 non-null    int32
 2   b_Self_emp_not_inc    983 non-null    int32
 3   b_Self_emp_inc        983 non-null    int32
 4   b_Without_pay         983 non-null    int32
 5   b_Local_gov           983 non-null    int32
 6   b_State_gov           983 non-null    int32
 7   b_Federal_gov         983 non-null    int32
 8   b_Private             983 non-null    int32
 9   b_Machine_op_inspct   983 non-null    int32
 10  b_Adm_clerical        983 non-null    int32
 11  b_Craft_repair        983 non-null    int32
 12  b_Exec_managerial     983 non-null    int32
 13  b_Farming_fishing     983 non-null    int32
 14  b_Handlers_cleaners   983 non-null    int32
 15  b_Other_service       983 non-null    int32
 16  b_Prof_speciality     983 non-null    int32
 17  b_Protective_serv     983 non-null    int32
 18  b_Sales               983 non-null    int32
 19  b_Tech_support        983 non-null    int32
 20  b_Transport_moving    983 non-null    int32
 21  b_Divorced            983 non-null    int32
 22  b_Married_civ_spouse  983 non-null    int32
 23  b_Never_married       983 non-null    int32
 24  b_Widowed             983 non-null    int32
 25  b_Separated           983 non-null    int32
 26  b_11th                983 non-null    int32
 27  b_Assoc_acdm          983 non-null    int32
 28  b_Bachelors           983 non-null    int32
 29  b_HS_grad             983 non-null    int32
 30  b_Some_college        983 non-null    int32
 31  b_10th                983 non-null    int32
 32  b_12th                983 non-null    int32
 33  b_1st_4th             983 non-null    int32
 34  b_5th_6th             983 non-null    int32
 35  b_7th_8th             983 non-null    int32
 36  b_9th                 983 non-null    int32
 37  b_Masters             983 non-null    int32
 38  b_Doctorate           983 non-null    int32
 39  b_Prof_school         983 non-null    int32
 40  type_of_client        983 non-null    int32
dtypes: int32(41)
memory usage: 165.1 KB

In [7]:
#importing package for train and test 
from sklearn.model_selection import train_test_split 

# preparing explanatory variable data --- (x data)
X   = flora_as.drop(['type_of_client'],
                               axis = 1)

# preparing response variables -- (y data)
y = flora_as.loc[ : ,'type_of_client'] # 1 - Personal / 0 - Wholesaler 

# creating the testing and training dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.25, 
    random_state = 219)

# checking the shapes of the datasets
print(f"""
Training Data
-------------
X-side: {X_train.shape}
y-side: {y_train.shape}


Testing Data
------------
X-side: {X_test.shape}
y-side: {y_test.shape}
""")

Training Data
-------------
X-side: (737, 42)
y-side: (737,)


Testing Data
------------
X-side: (246, 42)
y-side: (246,)

In [8]:
#Approaching logistic regression
# initiating model
logreg = LogisticRegression()

# fitting the model to training data
logreg.fit(X_train, y_train)

# Predict the labels of the test set: y_pred
y_pred = logreg.predict(X_test)

# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

#Showing training and testing scores
print(' Training Score:', logreg.score(X_train, y_train).round(4))
print(' Testing Score:', logreg.score(X_test, y_test).round(4))

logreg_train_score= logreg.score(X_train, y_train).round(4)
logreg_test_score =logreg.score(X_test, y_test).round(4)

#calculating the Gap between training and testing scores
print('Train-Test Gap:', abs(logreg_train_score - logreg_test_score).round(4))
logreg_test_gap =abs(logreg_train_score-logreg_test_score).round(4)

[[  3  45]
 [  6 192]]
              precision    recall  f1-score   support

           0       0.33      0.06      0.11        48
           1       0.81      0.97      0.88       198

    accuracy                           0.79       246
   macro avg       0.57      0.52      0.49       246
weighted avg       0.72      0.79      0.73       246

 Training Score: 0.8318
 Testing Score: 0.7927
Train-Test Gap: 0.0391

C:\Users\sejzi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [9]:
# Predicting based on unclassified data 

# Spliting no labeled dataset in 1s and 0s to identify the 2 types of client
unlabeled_data = flora_as.drop(['type_of_client'],
                               axis = 1)

new_pred_log = logreg.predict(unlabeled_data)

#Printing out the outcome of the splitting
print((new_pred_log))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]